services:
  - type: web
    name: aurora-forecast-uk
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: FB_PAGE_ID
        sync: false
      - key: FB_PAGE_ACCESS_TOKEN
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
